# Generated by Django 4.0.6 on 2022-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20)),
                ('Photo', models.ImageField(upload_to='media')),
                ('ContactNumber', models.CharField(max_length=13)),
                ('EmailAddress', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
