# Generated by Django 4.0.6 on 2022-07-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20)),
                ('Photo', models.ImageField(upload_to='media')),
                ('ContactNumber', models.CharField(max_length=13)),
                ('EmailAddress', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20)),
                ('Photo', models.ImageField(upload_to='media')),
                ('ContactNumber', models.CharField(max_length=13)),
                ('EmailAddress', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
