# Generated by Django 4.0.6 on 2022-07-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_clientmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduledDate', models.DateField()),
                ('clientlocation', models.CharField(max_length=20)),
                ('clientname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.clientmaster')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.inspector')),
            ],
        ),
    ]
